In [1]:
import numpy as np

In [2]:
p1 = np.array([[1, 0, 0, 0]])
p2 = np.array([[1, 1, 0, 0]])
p3 = np.array([[0, 0, 0, 1]])
p4 = np.array([[0, 0, 1, 1]])

t1 = np.array([[1, 0]])
t2 = np.array([[1, 0]])
t3 = np.array([[0, 1]])
t4 = np.array([[0, 1]])

In [3]:
p1_t = np.transpose(p1)
p2_t = np.transpose(p2)
p3_t = np.transpose(p3)
p4_t = np.transpose(p4)

In [4]:
w1 = np.matmul(p1_t, t1)
w2 = np.matmul(p2_t, t2)
w3 = np.matmul(p3_t, t3)
w4 = np.matmul(p4_t, t4)

In [5]:
total_weight = w1+w2+w3+w4
total_weight

array([[2, 0],
       [1, 0],
       [0, 1],
       [0, 2]])

In [6]:
test1 = np.array([[1, 0, 0, 0]])

In [7]:
def activation_function(net_output):
    for i in range(len(net_output)):
        for j in range(len(net_output[i])):
            if net_output[i][j] > 0:
                net_output[i][j] = 1
            else:
                net_output[i][j] = 0
    return net_output

In [8]:
net_output = np.matmul(test1,total_weight)
net_output

array([[2, 0]])

In [9]:
output = activation_function(net_output)
output

array([[1, 0]])

In [10]:
S=[[1,1,1,-1],[1,1,1,-1],[1,1,1,-1],[-1,-1,-1,1]]
w=np.matmul(np.transpose(S),[1,1,1,-1])

In [11]:
w

array([ 4,  4,  4, -4])

In [14]:
output = activation_function([w])
output

[array([1, 1, 1, 0])]