In [1]:
import numpy as np

In [2]:
input1=np.array([[1, 1, 1],
      [1, -1, -1],
      [1, 1, 1],
      [1, -1, -1],
      [1, 1, 1]])

target1 = np.array([[-1, 1]])

In [3]:
input1=input1.flatten()
input1

array([ 1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1])

In [4]:
input1=np.array([(input1)])
input1

array([[ 1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1]])

In [5]:
input1.shape

(1, 15)

In [6]:
w1=np.multiply((np.transpose(input1)),target1)
w1

array([[-1,  1],
       [-1,  1],
       [-1,  1],
       [-1,  1],
       [ 1, -1],
       [ 1, -1],
       [-1,  1],
       [-1,  1],
       [-1,  1],
       [-1,  1],
       [ 1, -1],
       [ 1, -1],
       [-1,  1],
       [-1,  1],
       [-1,  1]])

In [7]:
input2 = np.array([[1, 1, 1],
               [1, -1, -1],
               [1, 1, 1],
               [1, -1, -1],
               [1, -1, -1]])

input2 = input2.flatten()
input2 = np.array([input2])

In [8]:
target2=np.array([[1,1]])
w2=np.multiply(np.transpose(input2),target2)
w2

array([[ 1,  1],
       [ 1,  1],
       [ 1,  1],
       [ 1,  1],
       [-1, -1],
       [-1, -1],
       [ 1,  1],
       [ 1,  1],
       [ 1,  1],
       [ 1,  1],
       [-1, -1],
       [-1, -1],
       [ 1,  1],
       [-1, -1],
       [-1, -1]])

In [9]:
totalweight=w1+w2
totalweight

array([[ 0,  2],
       [ 0,  2],
       [ 0,  2],
       [ 0,  2],
       [ 0, -2],
       [ 0, -2],
       [ 0,  2],
       [ 0,  2],
       [ 0,  2],
       [ 0,  2],
       [ 0, -2],
       [ 0, -2],
       [ 0,  2],
       [-2,  0],
       [-2,  0]])

In [10]:
test1 = np.array([[1, 1, 1],
                 [1, -1, -1],
                 [1, 1, 1],
                 [1, -1, -1],
                 [1, 1, 1]])
test1 = test1.flatten()
test1 = np.array([test1])
test1

array([[ 1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1]])

In [11]:
test1.dtype

dtype('int32')

In [12]:
totalweight.dtype

dtype('int32')

In [13]:
y1_in=np.matmul(test1,totalweight)
y1_in

array([[-4, 26]])

In [14]:
def activation_function(net_output):
    for i in range(len(net_output)):
        for j in range(len(net_output[i])):
            if net_output[i][j] > 0:
                net_output[i][j] = 1
            else:
                net_output[i][j] = -1
    return net_output

In [15]:
output1 = activation_function(y1_in)
output1

array([[-1,  1]])